# Generated by Django 2.1.1 on 2021-11-13 07:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import farmer.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gu', djongo.models.fields.EmbeddedField(model_container=farmer.models.CategoryField, null=True)),
                ('en', djongo.models.fields.EmbeddedField(model_container=farmer.models.CategoryField, null=True)),
                ('image', models.ImageField(upload_to='category', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Profile Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=54, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('profile_photo', models.ImageField(upload_to='farmer', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Profile Photo')),
                ('contact', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')], verbose_name='Contact No')),
                ('village', models.CharField(max_length=20, verbose_name='Village')),
                ('postal_address', models.TextField(verbose_name='Postal Address')),
                ('cutomer_capacity', models.PositiveIntegerField(default=99999999999, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Customer-Capacity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.District', verbose_name='District')),
            ],
            options={
                'verbose_name_plural': 'farmers',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gu', djongo.models.fields.EmbeddedField(model_container=farmer.models.ProductField, null=True)),
                ('en', djongo.models.fields.EmbeddedField(model_container=farmer.models.ProductField, null=True)),
                ('image', models.ImageField(upload_to='Product', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Categories', verbose_name='Category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farmer', verbose_name='Farmer')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=40, unique=True, verbose_name='Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='farmer.Farmer', verbose_name='farmer')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.State', verbose_name='State'),
        ),
    ]
