# Generated by Django 3.2.8 on 2021-10-29 06:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('profile_photo', models.ImageField(upload_to='farmer', verbose_name='Profile Photo')),
                ('contact', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')], verbose_name='Contact No')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('district', models.CharField(max_length=50, verbose_name='district')),
                ('village', models.CharField(max_length=50, verbose_name='village')),
                ('postal_address', models.TextField(verbose_name='Postal Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'farmer',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=40, unique=True, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='farmer.farmer', verbose_name='farmer')),
            ],
        ),
    ]
