# Generated by Django 2.1.1 on 2021-11-13 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='cutomer_capacity',
            field=models.PositiveIntegerField(default=2147483647, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Customer-Capacity'),
        ),
    ]
