# Generated by Django 2.1.1 on 2021-11-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_district_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.District', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.State', verbose_name='State'),
        ),
    ]
