# Generated by Django 2.1.1 on 2021-11-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20211113_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='cutomer_capacity',
            new_name='customer_capacity',
        ),
    ]
