# Generated by Django 3.2.8 on 2021-11-01 05:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20211030_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, verbose_name='Name')),
                ('img', models.ImageField(upload_to='Product', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Image')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('stock', models.PositiveIntegerField(verbose_name='Product-Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.categories', verbose_name='Category')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer', verbose_name='Owner')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
