# Generated by Django 3.2.8 on 2021-11-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='token',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
