# Generated by Django 2.2.1 on 2021-12-24 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='village',
        ),
        migrations.AddField(
            model_name='farmer',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='gender',
            field=models.CharField(default='', max_length=50, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='pin_code',
            field=models.PositiveIntegerField(default=111111, validators=[django.core.validators.MinValueValidator(111111), django.core.validators.MaxValueValidator(999999)], verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='customer_capacity',
            field=models.PositiveIntegerField(default=2147483647, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Customer Capacity'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'active')], default='0', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='State'),
        ),
    ]
