# Generated by Django 2.2.1 on 2021-12-30 12:51

import django.core.validators
from django.db import migrations, models
import djongo.models.fields
import farmer.models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_auto_20211224_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='profile_video',
            field=models.FileField(default='', upload_to='farmer/video', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi'])], verbose_name='Profile Video'),
        ),
     
    ]
