# Generated by Django 2.1.1 on 2021-11-11 12:13

import customer.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('email', models.EmailField(max_length=54, unique=True, verbose_name='Email')),
                ('profile_photo', models.ImageField(upload_to='Customer', verbose_name='Profile Photo')),
                ('contact', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')], verbose_name='Contact No')),
                ('addresses', djongo.models.fields.ArrayField(model_container=customer.models.Address, verbose_name='Addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=40, unique=True, verbose_name='Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='customer.Customer', verbose_name='Customer')),
            ],
        ),
    ]
