# Generated by Django 2.2.24 on 2021-11-09 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(111111), django.core.validators.MaxValueValidator(999999)], verbose_name='Pincode'),
        ),
    ]
