# Generated by Django 2.1.1 on 2021-11-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20211113_0741'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='farmer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='farmer.Farmer', verbose_name='Farmer'),
        ),
    ]
