# Generated by Django 2.1.1 on 2021-11-13 08:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20211113_0749'),
        ('customer', '0002_customer_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='product_qty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('product_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Products', verbose_name='Product-item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
    ]
