# Generated by Django 2.1.1 on 2021-11-15 09:30

import customer.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=djongo.models.fields.ArrayField(default='', model_container=customer.models.CartField, verbose_name='Items'),
        ),
    ]
