# Generated by Django 2.1.1 on 2021-11-16 07:44

import customer.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import farmer.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20211115_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('products', djongo.models.fields.ArrayField(model_container=farmer.models.Products, verbose_name='products')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Product-qty')),
                ('total', models.PositiveIntegerField(verbose_name='Total-Amount')),
                ('address', models.TextField(verbose_name='Address')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment-Method')),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Dispatched'), ('3', 'Delievered'), ('4', 'Cancelled')], default='0', max_length=50, verbose_name='status')),
                ('ordered_date', models.DateField(auto_now_add=True, verbose_name='Ordered-Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='user')),
            ],
        ),
        
    ]
