# Generated by Django 2.1.1 on 2021-11-17 12:52

import customer.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20211113_0749'),
        ('customer', '0006_auto_20211116_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='order',
            name='farmer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='farmer.Farmer', verbose_name=''),
        ),
    ]
