# Generated by Django 2.1.1 on 2021-11-17 13:14

import customer.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20211117_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Dispatched'), ('3', 'Delievered'), ('4', 'Cancelled')], default='pending', max_length=50, verbose_name='status'),
        ),
       
    ]
