# Generated by Django 2.1.1 on 2021-11-18 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0004_farmer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=54, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('profile_photo', models.ImageField(upload_to='farmer', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Profile Photo')),
                ('contact', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')], verbose_name='Contact No')),
                ('postal_address', models.TextField(verbose_name='Postal Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.District', verbose_name='District')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.State', verbose_name='State')),
            ],
            options={
                'verbose_name_plural': 'Admin',
            },
        ),
    ]
