# Generated by Django 2.1.1 on 2021-11-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmer_status'),
        ('subadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='SubAdmin',
        ),
    ]
