# Generated by Django 2.1.1 on 2021-11-18 13:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0002_auto_20211118_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=40, unique=True, verbose_name='Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to='subadmin.SubAdmin', verbose_name='Admin')),
            ],
        ),
    ]
